// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SetContentElement } from "./SetContentElement";

export interface Inventory { sets: Record<string, number>, extra_elements: Record<SetContentElement, number>, }