// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Name } from "./Name";
import type { SetContentElement } from "./SetContentElement";

export interface Set { id: string, names: Array<Name>, content: Record<SetContentElement, number>, }